#!/usr/bin/env bash

bake_require github.com/kyleburton/bake-recipies/emacs/cider.sh

bake_task run-emacs "Run emacs with Kyle's configuration"
function run-emacs () {
  emacs -nw -q -l $HOME/.bake/packages/github.com/kyleburton/bake-recipies/files/emacs/.emacs "$@"
}

bake_task run-dev "Run the project's main (the NREPL server)"
function run-dev () {
  lein with-profile +dev run -m corpus-enormous.nrepl
}

# bake_task gen-rand-email-file "Generate a random list of emails."
# function gen-rand-email-file () {
#   lein run  -m data-talk.core generate-email-address-file
# }


bake_task get-tlds
function get-tlds () {
  local url="http://www.iana.org/domains/root/db"
  local htmlfile="resources/corpus-enormous/internet/iana.org-tlds.html"
  local tldfile="resources/corpus-enormous/internet/tlds.txt"
  test -f "$htmlfile" || curl "$url" > "$htmlfile"
  if [ ! -e $tldfile ]; then
    grep 'domain tld' resources/corpus-enormous/internet/iana.org-tlds.html | cut -d'>' -f3- | cut -f1 -d'<' > $tldfile
  fi
}
